version: "3.8"

services:
  gitguard-engine:
    build: .
    container_name: gitguard_api
    command: uvicorn engine:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./commit_logs.csv:/app/commit_logs.csv

  gitguard-dashboard:
    build: .
    container_name: gitguard_ui
    command: streamlit run dashboard.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./commit_logs.csv:/app/commit_logs.csv
    depends_on:
      - gitguard-engine
